TURN_COUNT = 50
ITERATIONS_PER_MOVE = 5
MAX_SIMULATION_DEPTH = 15
BEST_MOVE_SELECTION_CANDIDATES = 30
WHITE_VALUE_FUNCTION_COEFFICIENTS = [-10, -2, 2, -2, 5]
BLACK_VALUE_FUNCTION_COEFFICIENTS = [10, 2, -2, 2, -5]
