"""initial

Revision ID: 649ba19e24e1
Revises: 
Create Date: 2023-03-08 23:56:14.361825

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '649ba19e24e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'game',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('host_id', sa.Integer(), nullable=False),
        sa.Column('guest_id', sa.Integer(), nullable=False),
        sa.Column('host_played_first', sa.Boolean(),
                  nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True),
                  nullable=True),
        sa.Column('finished_at', sa.DateTime(timezone=True),
                  nullable=True),
        sa.Column('board_state', sa.String(length=169),
                  nullable=True),
        sa.Column('host_current_turn', sa.Boolean(), nullable=True),
        sa.Column('history', sa.String(), nullable=True),
        sa.Column('result',
                  sa.Enum('unfinished', 'host_win', 'guest_win',
                          name='gamestatus'), nullable=True),
        sa.ForeignKeyConstraint(['guest_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('user')
    # ### end Alembic commands ###
