"""is_bot

Revision ID: 8e63b35101bf
Revises: 649ba19e24e1
Create Date: 2023-03-09 00:15:41.144571

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8e63b35101bf'
down_revision = '649ba19e24e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # You cant just add non-nullable column because you must
    #   set defaults for existing row.
    op.execute('UPDATE "user" SET is_bot=false')
    op.alter_column('user', 'is_bot', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_bot')
    # ### end Alembic commands ###
