"""mapped_tables

Revision ID: c85e45a0d668
Revises: cc3b1e0214c3
Create Date: 2023-04-11 21:27:32.361445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c85e45a0d668'
down_revision = 'cc3b1e0214c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Change null to default game history (empty string).
    op.execute('UPDATE "game" SET history=\'\'')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('ended_at', sa.DateTime(timezone=True),
                                    nullable=True))
    op.alter_column('game', 'started_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    op.alter_column('game', 'host_current_turn',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('game', 'history',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('game', 'result',
                    existing_type=postgresql.ENUM('unfinished', 'host_win',
                                                  'guest_win',
                                                  name='gamestatus'),
                    nullable=False)
    op.drop_column('game', 'finished_at')
    op.drop_column('game', 'board_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('board_state', sa.VARCHAR(length=169),
                                    autoincrement=False, nullable=True))
    op.add_column('game',
                  sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True),
                            autoincrement=False, nullable=True))
    op.alter_column('game', 'result',
                    existing_type=postgresql.ENUM('unfinished', 'host_win',
                                                  'guest_win',
                                                  name='gamestatus'),
                    nullable=True)
    op.alter_column('game', 'history',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('game', 'host_current_turn',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('game', 'started_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    op.drop_column('game', 'ended_at')
    # ### end Alembic commands ###
